apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alertmanager.fullname" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "alertmanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "alertmanager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: alertmanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
            - name: data
              mountPath: /alertmanager
            {{- if .Values.slack.enabled }}
            - name: slack-secret
              mountPath: /etc/alertmanager/secrets
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 20
      volumes:
        - name: config
          configMap:
            name: {{ include "alertmanager.fullname" . }}-config
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "alertmanager.fullname" . }}-pvc
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- if .Values.slack.enabled }}
        - name: slack-secret
          secret:
            secretName: {{ .Values.slack.existingSecretName }}
        {{- end }}
