apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebeat.fullname" . }}-config
  labels:
    {{- include "filebeat.labels" . | nindent 4 }}
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          templates:
            - condition:
                equals:
                  kubernetes.namespace: {{ .Values.watchNamespace }}
              config:
                - type: container
                  paths:
                    - /var/log/containers/*${data.kubernetes.container.id}.log

    processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    output.logstash:
      hosts: ["{{ .Values.logstash.host }}"]

    logging.level: info
