apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.prometheus.host }}
        isDefault: true
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-dashboard-provider
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  provider.yml: |
    apiVersion: 1
    providers:
      - name: enterprise-devops
        orgId: 1
        folder: "Enterprise DevOps"
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
