apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}-headless
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
  ports:
    - name: transport
      port: {{ .Values.service.transportPort }}
      targetPort: transport
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
